### ISSUE TITLE
Support for XML format in FetchUtil

### ISSUE THREAD

**Issue by laichengyu** [CS2103JAN2018-F09-B3/main#69]
* If we are still going to use Cryptopanic API, XML format needs to be supported by FetchUtil for Cryptopanic's news posts

**Comment by ewaldhew** [comment]
I think not; their license terms not suitable for us. I forgot to mention during the meeting but maybe we just  grab some news from RSS feeds, instead of API. Difference is we lose coin-specific metadata like coin tag for which news is relevant, etc. So we cant have coin-specific news panel but we can still demo I guess.

**Comment by laichengyu** [comment]
Sounds fine to me
